# Generated by Django 2.2.13 on 2020-07-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonCategory',
            new_name='Category',
        ),
    ]
