# Generated by Django 2.2.13 on 2020-07-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='comments_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
