# Generated by Django 2.2.13 on 2020-07-22 11:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20200715_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='tags',
        ),
        migrations.AddField(
            model_name='lesson',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
